HDDSstack <- dat

HDDSstack$GrainsRootsTubers_source_good <- ifelse(is.na(HDDSstack$GrainsRootsTubers_source_good), HDDSstack$GrainsRootsTubers_source_last_month, HDDSstack$GrainsRootsTubers_source_good)
HDDSstack$VitA_Veg_Fruit_source_good <- ifelse(is.na(HDDSstack$VitA_Veg_Fruit_source_good), HDDSstack$VitA_Veg_Fruit_source_last_month, HDDSstack$VitA_Veg_Fruit_source_good)
HDDSstack$Veg_Leafy_source_good <- ifelse(is.na(HDDSstack$Veg_Leafy_source_good), HDDSstack$Veg_Leafy_source_last_month, HDDSstack$Veg_Leafy_source_good)
HDDSstack$Vegetables_source_good <- ifelse(is.na(HDDSstack$Vegetables_source_good), HDDSstack$Vegetables_source_last_month, HDDSstack$Vegetables_source_good)
HDDSstack$Nuts_Seeds_source_good <- ifelse(is.na(HDDSstack$Nuts_Seeds_source_good), HDDSstack$Nuts_Seeds_source_last_month, HDDSstack$Nuts_Seeds_source_good)
HDDSstack$Fruits_source_good <- ifelse(is.na(HDDSstack$Fruits_source_good), HDDSstack$Fruits_source_last_month, HDDSstack$Fruits_source_good)
HDDSstack$Legumes_source_good <- ifelse(is.na(HDDSstack$Legumes_source_good), HDDSstack$Legumes_source_last_month, HDDSstack$Legumes_source_good)
HDDSstack$Milk_Dairy_source_good <- ifelse(is.na(HDDSstack$Milk_Dairy_source_good), HDDSstack$Milk_Dairy_source_last_month, HDDSstack$Milk_Dairy_source_good)
HDDSstack$Meat_source_good <- ifelse(is.na(HDDSstack$Meat_source_good), HDDSstack$Meat_source_last_month, HDDSstack$Meat_source_good)
HDDSstack$Eggs_source_good <- ifelse(is.na(HDDSstack$Eggs_source_good), HDDSstack$Eggs_source_last_month, HDDSstack$Eggs_source_good)

HDDSstack$iHDDSsourcegrRT_good <- paste(HDDSstack$iHDDSgrRT_good, HDDSstack$GrainsRootsTubers_source_good, sep = "@")
HDDSstack$iHDDSsourcevegA_good <- paste(HDDSstack$iHDDSvegA_good, HDDSstack$VitA_Veg_Fruit_source_good, sep = "@")
HDDSstack$iHDDSsourcevegL_good <- paste(HDDSstack$iHDDSvegL_good, HDDSstack$Veg_Leafy_source_good, sep = "@")
HDDSstack$iHDDSsourcevegO_good <- paste(HDDSstack$iHDDSvegO_good, HDDSstack$Vegetables_source_good, sep = "@")
HDDSstack$iHDDSsourcenutS_good <- paste(HDDSstack$iHDDSnutS_good, HDDSstack$Nuts_Seeds_source_good, sep = "@")
HDDSstack$iHDDSsourcefru_good <- paste(HDDSstack$iHDDSfru_good, HDDSstack$Fruits_source_good, sep = "@")
HDDSstack$iHDDSsourceleg_good <- paste(HDDSstack$iHDDSleg_good, HDDSstack$Legumes_source_good, sep = "@")
HDDSstack$iHDDSsourcemilk_good <- paste(HDDSstack$iHDDSmilk_good, HDDSstack$Milk_Dairy_source_good, sep = "@")
HDDSstack$iHDDSsourcemeat_good <- paste(HDDSstack$iHDDSmeat_good, HDDSstack$Meat_source_good, sep = "@")
HDDSstack$iHDDSsourceeggs_good <- paste(HDDSstack$iHDDSeggs_good, HDDSstack$Eggs_source_good, sep = "@")

HDDSstack$GrainsRootsTubers_source_bad <- ifelse(is.na(HDDSstack$GrainsRootsTubers_source_bad), HDDSstack$GrainsRootsTubers_source_last_month, HDDSstack$GrainsRootsTubers_source_bad)
HDDSstack$VitA_Veg_Fruit_source_bad <- ifelse(is.na(HDDSstack$VitA_Veg_Fruit_source_bad), HDDSstack$VitA_Veg_Fruit_source_last_month, HDDSstack$VitA_Veg_Fruit_source_bad)
HDDSstack$Veg_Leafy_source_bad <- ifelse(is.na(HDDSstack$Veg_Leafy_source_bad), HDDSstack$Veg_Leafy_source_last_month, HDDSstack$Veg_Leafy_source_bad)
HDDSstack$Vegetables_source_bad <- ifelse(is.na(HDDSstack$Vegetables_source_bad), HDDSstack$Vegetables_source_last_month, HDDSstack$Vegetables_source_bad)
HDDSstack$Nuts_Seeds_source_bad <- ifelse(is.na(HDDSstack$Nuts_Seeds_source_bad), HDDSstack$Nuts_Seeds_source_last_month, HDDSstack$Nuts_Seeds_source_bad)
HDDSstack$Fruits_source_bad <- ifelse(is.na(HDDSstack$Fruits_source_bad), HDDSstack$Fruits_source_last_month, HDDSstack$Fruits_source_bad)
HDDSstack$Legumes_source_bad <- ifelse(is.na(HDDSstack$Legumes_source_bad), HDDSstack$Legumes_source_last_month, HDDSstack$Legumes_source_bad)
HDDSstack$Milk_Dairy_source_bad <- ifelse(is.na(HDDSstack$Milk_Dairy_source_bad), HDDSstack$Milk_Dairy_source_last_month, HDDSstack$Milk_Dairy_source_bad)
HDDSstack$Meat_source_bad <- ifelse(is.na(HDDSstack$Meat_source_bad), HDDSstack$Meat_source_last_month, HDDSstack$Meat_source_bad)
HDDSstack$Eggs_source_bad <- ifelse(is.na(HDDSstack$Eggs_source_bad), HDDSstack$Eggs_source_last_month, HDDSstack$Eggs_source_bad)


HDDSstack$iHDDSsourcegrRT_bad <- paste(HDDSstack$iHDDSgrRT_bad, HDDSstack$GrainsRootsTubers_source_bad, sep = "@")
HDDSstack$iHDDSsourcevegA_bad <- paste(HDDSstack$iHDDSvegA_bad, HDDSstack$VitA_Veg_Fruit_source_bad, sep = "@")
HDDSstack$iHDDSsourcevegL_bad <- paste(HDDSstack$iHDDSvegL_bad, HDDSstack$Veg_Leafy_source_bad, sep = "@")
HDDSstack$iHDDSsourcevegO_bad <- paste(HDDSstack$iHDDSvegO_bad, HDDSstack$Vegetables_source_bad, sep = "@")
HDDSstack$iHDDSsourcenutS_bad <- paste(HDDSstack$iHDDSnutS_bad, HDDSstack$Nuts_Seeds_source_bad, sep = "@")
HDDSstack$iHDDSsourcefru_bad <- paste(HDDSstack$iHDDSfru_bad, HDDSstack$Fruits_source_bad, sep = "@")
HDDSstack$iHDDSsourceleg_bad <- paste(HDDSstack$iHDDSleg_bad, HDDSstack$Legumes_source_bad, sep = "@")
HDDSstack$iHDDSsourcemilk_bad <- paste(HDDSstack$iHDDSmilk_bad, HDDSstack$Milk_Dairy_source_bad, sep = "@")
HDDSstack$iHDDSsourcemeat_bad <- paste(HDDSstack$iHDDSmeat_bad, HDDSstack$Meat_source_bad, sep = "@")
HDDSstack$iHDDSsourceeggs_bad <- paste(HDDSstack$iHDDSeggs_bad, HDDSstack$Eggs_source_bad, sep = "@")

HDDSstack <- select(HDDSstack, contains("iHDDSsource"), HouseholdID, country, region, HDDSgood, HDDSbad)
HDDSstack_long <- gather(HDDSstack, key, val, contains("iHDDS"))
HDDSstack_long <- separate(HDDSstack_long, key, c("Category", "Season"), sep = "_")
HDDSstack_long <- separate(HDDSstack_long, val, c("val", "Source"), sep = "@")
HDDSstack_long$Category <- gsub("iHDDSsource", "", HDDSstack_long$Category)
HDDSstack_long$Source <- gsub("both", "on-farm bought", HDDSstack_long$Source)
HDDSstack_long$Source <- gsub("onfarm", "on-farm", HDDSstack_long$Source)
HDDSstack_long$Source <- gsub("off-farm", "bought", HDDSstack_long$Source)
HDDSstack_long$onFarm <- grepl("on-farm", HDDSstack_long$Source)
HDDSstack_long$bought <- grepl("bought", HDDSstack_long$Source)
HDDSstack_long$Source <- gsub("gift_exchange", "free", HDDSstack_long$Source)
#!Treat gathered and exchanged the same as 'free'
HDDSstack_long$Source <- gsub("gathered", "free", HDDSstack_long$Source)
HDDSstack_long$free <- grepl("free", HDDSstack_long$Source)

summaryHDDSstack <- group_by(HDDSstack_long, HouseholdID, Season)
summaryHDDSstack <- summaryHDDSstack[summaryHDDSstack$val != 0,]
summaryHDDSstack <- summarise(summaryHDDSstack, HDDSonFarm =sum(onFarm, na.rm=T), HDDSpurchased = sum(bought, na.rm=T))
summaryHDDSstack <- unite(summaryHDDSstack, "onFarm_purchased", c("HDDSonFarm", "HDDSpurchased"))
summaryHDDSstack <- spread(summaryHDDSstack, Season, onFarm_purchased)
summaryHDDSstack <- separate(summaryHDDSstack, bad, c("HDDSonFarmBad", "HDDSpurchasedBad"))
summaryHDDSstack <- separate(summaryHDDSstack, good, c("HDDSonFarmGood", "HDDSpurchasedGood"))

HDDSstack_long <- left_join(HDDSstack_long, select(summaryHDDSstack, HouseholdID, HDDSonFarmGood, HDDSonFarmBad, HDDSpurchasedGood, HDDSpurchasedBad))

